FROM python:3.8

ENV PYTHONUNBUFFERED=1

RUN python -m pip install --upgrade pip

WORKDIR /home/docker

# COPY requirements/ requirements/
RUN python -m pip install celery==4.4.7

COPY celeryapp .


CMD ["celery", "-A", "tasks", "worker", "-l", "INFO", "-Q", "arithmetic,geometry"]
