version: "3"

services:
  app:
    image: taskrabbit
    volumes:
      - ./:/home/docker

  worker:
    build:
      dockerfile: Dockerfile.celeryworker
      context: .

  tasks:
    build:
      dockerfile: Dockerfile.celeryworker
      context: .
    command: python make_tasks.py

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: taskrabbit
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

volumes:
  .postgres_data: